# Generated by Django 4.0.2 on 2022-03-28 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('OTP', models.IntegerField()),
                ('role', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPostDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(default='', max_length=250)),
                ('companyname', models.CharField(default='', max_length=250)),
                ('companyaddress', models.CharField(default='', max_length=250)),
                ('jobsdescription', models.TextField(default='', max_length=500)),
                ('qualification', models.CharField(default='', max_length=250)),
                ('responsibilities', models.CharField(default='', max_length=250)),
                ('location', models.CharField(default='', max_length=250)),
                ('companywebsite', models.CharField(default='', max_length=250)),
                ('companyemail', models.CharField(default='', max_length=250)),
                ('companycontact', models.CharField(default='', max_length=20)),
                ('salarypackage', models.CharField(default='', max_length=250)),
                ('experience', models.IntegerField()),
                ('logo', models.ImageField(upload_to='JobPostImage/')),
                ('Resume', models.FileField(upload_to='Resume/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermaster')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('website', models.CharField(default='', max_length=250)),
                ('desciption', models.CharField(default='', max_length=500)),
                ('logo_pc', models.ImageField(upload_to='CompanyImage/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermaster')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('dob', models.CharField(max_length=50)),
                ('profession', models.CharField(default='', max_length=100)),
                ('current_salary', models.BigIntegerField()),
                ('expected_salary', models.BigIntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('shift', models.CharField(default='', max_length=20)),
                ('job_discription', models.CharField(default='', max_length=100)),
                ('profile_pic', models.ImageField(upload_to='CandidateImage/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermaster')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('Resume', models.FileField(upload_to='app/Resume/')),
                ('Candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidate')),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobpostdetails')),
            ],
        ),
    ]
