# Generated by Django 4.0.2 on 2022-04-13 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_applylist_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='applylist',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.usermaster'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applylist',
            name='Candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidate'),
        ),
    ]
